### PR TITLE
feat(datepicker): add button to clear value

### PR DESCRIPTION
**Pull request by raulsteurer**

### CODE REVIEW

**Review by lukasbals — COMMENTED** [review]
Screenshot 2024-08-13 at 11 24 45

In the actions in the Storybook I only see the `onSelect` events, but no `onChange` event? Could we change that to see both of them?

**Comment by raulsteurer** [comment]
> In the actions in the Storybook I only see the `onSelect` events, but no `onChange` event? Could we change that to see both of them?

This is because we provide the `setState` function to the `onChange` prop:

image

The `onChange` events get logged if I remove that prop, but then the value never changes

**Comment by lukasbals** [comment]
> > In the actions in the Storybook I only see the `onSelect` events, but no `onChange` event? Could we change that to see both of them?
> 
> This is because we provide the `setState` function to the `onChange` prop:
> 
> image
> 
> The `onChange` events get logged if I remove that prop, but then the value never changes

Ok. Fair. Then let's keep it this way.

**Review by lukasbals — APPROVED** [review]
LGTM.

Did you check if it works with the `BoemlyFormControl` component?

**Pull request merged**
